### ISSUE TITLE
Add ktlint

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/BunnyBots-2019#15]
`ktlint` enforces correct formatting throughout the codebase, which leads to a consistent style and easier to read code. See [here](https://github.com/SouthEugeneRoboticsTeam/DeepSpace-2019/blob/development/build.gradle) for an example.

## Steps

- [ ] Copy over all lines from the [file above](https://github.com/SouthEugeneRoboticsTeam/DeepSpace-2019/blob/development/build.gradle) with `ktlint`
- [ ] Run `./gradlew check` or `./gradlew build` and see if there are any issues
- [ ] If there are linting issues, fix them as part of this pull request
- [ ] Submit a pull request with your changes!

**Comment by mckelveygreg** [comment]
I'd also add a `pre-commit` hook so you never have to worry about un-linted code getting committed! 
I found this on https://ktlint.github.io/:
```
# install git hook to automatically check files for style violations on commit
$ ktlint --install-git-pre-commit-hooks
```
