### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by gnawinganimal** [SouthEugeneRoboticsTeam/BunnyBots-2019#3]
Without the drivetrain, we can't really... move. Owning this subsystem does not mean that you have to program the entirety of the autonomous mode by yourself, just make it so that the driver can control it. We are also not 100% sure if we are using mechanisms or not, so we might have to wait for this.

**Comment by will-hou** [comment]
Mecanums are officially off the table now so we can go ahead and program a standard tank drivetrain. 

See https://github.com/SouthEugeneRoboticsTeam/DeepSpace-2019/blob/development/src/main/kotlin/org/sert2521/deepspace/drivetrain/Drivetrain.kt

**Comment by codingvic** [comment]
Yeah!!!

**Comment by will-hou** [comment]
Closed by #8
